#! /bin/sh

### BSPWM config ###

bspc monitor DVI-I-1 -d VI VII VIII IX X
bspc monitor HDMI-0 -d I II III IV V

background=080909
foreground=cbd7d6
active=4d4d4d

bspc config border_width         6
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#$background"
bspc config active_border_color "#$active"
bspc config focused_border_color "#$active"
bspc config presel_feedback_color "#$active"

# Rules
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a zathura state=tiled
# Panel
/home/jon/.config/polybar/launch.sh &

# Compositor
compton --config ~/.config/compton.conf -b &

# Desktop notifications
dunst &

# Start sxhkd
sxhkd &

# Background Wallpapers
feh --bg-scale /jonfiles/Pictures/Backgrounds/snow_tree_1.jpg/ --bg-scale /jonfiles/Pictures/Backgrounds/snow_tree_2.jpg/
